<?php
$jogadores = [
    'barou' => [
        'id' => 'barou',
        'nome' => 'Shoei Barou',
        'titulo' => 'KING LION',
        'meta_tag' => '// FW - SHOEI BAROU //',
        'subtitulo_card' => 'SHOEI BAROU',
        'cor_borda' => '#d40606',
        'cor_texto' => 'corLetra',
        'gif' => 'assets/img/gif/barou-barou-goal.gif',
        'musica' => 'assets/img/music/BarouTheme.mp3',
        'musica_titulo' => 'KING- ばろう',
        'musica_artista' => 'Shoei Barou',
        'capa_musica' => 'assets/img/img/baromusic.png',
        'icon' => 'assets/img/img/BL_Icon_Shoei_Baro.webp',
        'posicao' => 'ATTACKING | KING',
        'overall' => 92,
        'rank' => 'RANK S',
        'rank_badge' => 'S',
        'badge' => 'JOKER',
        'stats' => ['SHT' => [96, ''], 'DEF' => [68, ''], 'SPD' => [80, ''], 'DRI' => [88, ''], 'PSS' => [61, '']],
        'descricao' => 'Na liga italiana de Blue Lock, Barou se tornou o líder do Ubers...'
    ],
    'zombie' => [
        'id' => 'zombie',
        'nome' => 'Don Lorenzo',
        'titulo' => 'ACE EATER',
        'meta_tag' => '// CB - DON LORENZO //',
        'subtitulo_card' => 'DON LORENZO',
        'cor_borda' => '#461a3f',
        'cor_texto' => 'corLetra',
        'gif' => 'assets/img/gif/don-lorenzo-music.gif',
        'musica' => 'assets/img/music/ViolinSky_LightintheDark.mp3',
        'musica_titulo' => 'ZOMBIE - Don Lorenzo',
        'musica_artista' => 'Don Lorenzo 🧟',
        'capa_musica' => 'assets/img/img/donlorenzo5.png',
        'icon' => 'assets/img/img/donlorenzoicon.png',
        'posicao' => 'DEFENDER | ZOMBIE DRIBBLING',
        'overall' => 96,
        'rank' => 'RANK S',
        'rank_badge' => 'S',
        'badge' => 'CB',
        'stats' => ['SHT' => [78, ''], 'DEF' => [99, ''], 'SPD' => [85, ''], 'DRI' => [93, ''], 'PSS' => [87, '']],
        'descricao' => 'Conhecido como "Comedor de Ases", Don Lorenzo é o pilar defensivo da equipe e membro do World 11...'
    ],
    'sendou' => [
        'id' => 'sendou',
        'nome' => 'Shuto Sendo',
        'titulo' => 'Ás Oculto',
        'meta_tag' => '// ST - SHUTO SENDO //',
        'subtitulo_card' => 'SHUTO SENDO',
        'cor_borda' => '#ffa500',
        'cor_texto' => 'corLetra',
        'gif' => 'assets/img/gif/sendou.gif',
        'musica' => 'assets/img/music/Sendou_vs_Everyone.mp3',
        'musica_titulo' => 'The Shadow Ace',
        'musica_artista' => 'Shuto Sendo ⚽',
        'capa_musica' => 'assets/img/img/sendou.jpg',
        'icon' => 'assets/img/img/sendouicon.webp',
        'posicao' => 'S ATTACKING | TEAMWORK',
        'overall' => 81,
        'rank' => 'RANK A',
        'rank_badge' => 'A',
        'badge' => 'SA',
        'stats' => ['SHT' => [83, ''], 'DEF' => [73, ''], 'SPD' => [82, ''], 'DRI' => [77, ''], 'PSS' => [76, '']],
        'descricao' => 'Shuto Sendo, segundo atacante do Ubers. O papel principal dele é criar espaço para o Barou...'
    ],
    'niko' => [
        'id' => 'niko',
        'nome' => 'Ikki Niko',
        'titulo' => 'Olhos da Metavisão',
        'meta_tag' => '// DMF - IKKI NIKO //',
        'subtitulo_card' => 'IKKI NIKO',
        'cor_borda' => '#1278cc',
        'cor_texto' => 'corLetra',
        'gif' => 'assets/img/gif/niko2.gif',
        'musica' => 'assets/img/music/NikoMusic.mp3',
        'musica_titulo' => 'águia - 一揮 二子',
        'musica_artista' => 'Ikki Niko 🦅',
        'capa_musica' => 'assets/img/img/niko5.jpg',
        'icon' => 'assets/img/img/niko.webp',
        'posicao' => 'MIDFIELDER | META VISION',
        'overall' => 82,
        'rank' => 'RANK A',
        'rank_badge' => 'A',
        'badge' => 'VOL',
        'stats' => ['SHT' => [67, ''], 'DEF' => [84, ''], 'SPD' => [78, ''], 'DRI' => [76, ''], 'PSS' => [88, '']],
        'descricao' => 'Ikki Niko usa a Metavision para escanear cada jogador e prever os espaços no campo...'
    ],
    'aryu' => [
        'id' => 'aryu',
        'nome' => 'Jyubei Aryu',
        'titulo' => 'GLAM',
        'meta_tag' => '// CB - JYUBEI ARYU //',
        'subtitulo_card' => 'JYUBEI ARYU',
        'cor_borda' => '#e6007e',
        'cor_texto' => 'corLetra',
        'gif' => 'assets/img/gif/aryujyubei.gif',
        'musica' => 'assets/img/music/ViolinSky_LightintheDark.mp3',
        'musica_titulo' => 'GLAM - Aryu',
        'musica_artista' => 'Jyubei Aryu ✨',
        'capa_musica' => 'assets/img/img/aryumusic.png',
        'icon' => 'assets/img/img/jyubeiicon.webp',
        'posicao' => 'DEFENDER | GLAMOUR',
        'overall' => 84,
        'rank' => 'RANK A',
        'rank_badge' => 'A',
        'badge' => 'CB',
        'stats' => ['SHT' => [71, ''], 'DEF' => [88, ''], 'SPD' => [83, ''], 'DRI' => [75, ''], 'PSS' => [70, '']],
        'descricao' => 'Com um alcance físico avantajado, Aryu domina as bolas aéreas com um estilo único e estiloso...'
    ],
    'aiku' => [
        'id' => 'aiku',
        'nome' => 'Oliver Aiku',
        'titulo' => 'Cobra',
        'meta_tag' => '// CB - OLIVER AIKU //',
        'subtitulo_card' => 'OLIVER AIKU',
        'cor_borda' => '#9a06d4',
        'cor_texto' => 'corLetra',
        'gif' => 'assets/img/gif/aikugif1.gif',
        'musica' => 'assets/img/music/AikuTheme.mp3',
        'musica_titulo' => 'COBRA- オリヴァ 愛空',
        'musica_artista' => 'Aiku 🐍',
        'capa_musica' => 'assets/img/img/aikucobra.jpg',
        'icon' => 'assets/img/img/BL_Icon_Oliver_Aiku.webp',
        'posicao' => 'DEFENDER | META VISION',
        'overall' => 85,
        'rank' => 'RANK A',
        'rank_badge' => 'A',
        'badge' => 'Capitão',
        'stats' => ['SHT' => [77, ''], 'DEF' => [93, ''], 'SPD' => [81, ''], 'DRI' => [76, ''], 'PSS' => [83, '']],
        'descricao' => 'Aiku é o capitão e o coração da defesa. Possui inteligência tática para prever jogadas na área...'
    ]
];
?>